In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Aviral\OneDrive\Desktop\EDA project\Spatiotemporal-Analysis-of-Ride-Hailing-Demand-and-Cancellation-Patterns-in-Delhi-NCR\data\raw\ncr_rides_final_event_dataset_2024.csv")
df.head(5)

,datetime,Date,Time,year,month,day,weekday,hour,ride_date,Event,...,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23 12:29:38,2024-03-23,12:29:38,2024,3,23,Saturday,12,2024-03-23,Normal Day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29 18:01:39,2024-11-29,18:01:39,2024,11,29,Friday,18,2024-11-29,Wedding_Season,...,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,NaN,NaN,UPI
2,2024-08-23 08:56:10,2024-08-23,08:56:10,2024,8,23,Friday,8,2024-08-23,Monsoon,...,25.8,NaN,NaN,NaN,NaN,NaN,NaN,4.9,4.9,Debit Card
3,2024-10-21 17:17:25,2024-10-21,17:17:25,2024,10,21,Monday,17,2024-10-21,Normal Day,...,28.5,NaN,NaN,NaN,NaN,NaN,NaN,4.6,5.0,UPI
4,2024-09-16 22:08:00,2024-09-16,22:08:00,2024,9,16,Monday,22,2024-09-16,Normal Day,...,19.6,NaN,NaN,NaN,NaN,NaN,NaN,4.1,4.3,UPI

In [4]:
rows=df.shape[0]
columns=df.shape[1]
print("Number of Columns:",columns)
print("Number of Rows:",rows)
print("Columns in DataSet:\n",df.columns)

Number of Columns: 29
Number of Rows: 160609
Columns in DataSet:
 Index(['datetime', 'Date', 'Time', 'year', 'month', 'day', 'weekday', 'hour',
       'ride_date', 'Event', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Ride Distance',
       'Booking Value', 'Avg VTAT', 'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Driver Ratings', 'Customer Rating',
       'Payment Method'],
      dtype='str')

In [5]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 160609 entries, 0 to 160608
Data columns (total 29 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   datetime                           160609 non-null  str
 1   Date                               160609 non-null  str
 2   Time                               160609 non-null  str
 3   year                               160609 non-null  int64
 4   month                              160609 non-null  int64
 5   day                                160609 non-null  int64
 6   weekday                            160609 non-null  str
 7   hour                               160609 non-null  int64
 8   ride_date                          160609 non-null  str
 9   Event                              160609 non-null  str
 10  Booking ID                         160609 non-null  str
 11  Booking Status                     160609 non-null  str
 12  Customer ID                        160609 non-null  str
 13  Vehicle Type                       160609 non-null  str
 14  Pickup Location                    160609 non-null  str
 15  Drop Location                      160609 non-null  str
 16  Ride Distance                      109329 non-null  float64
 17  Booking Value                      109329 non-null  float64
 18  Avg VTAT                           149402 non-null  float64
 19  Avg CTAT                           109329 non-null  float64
 20  Cancelled Rides by Customer        11254 non-null   float64
 21  Reason for cancelling by Customer  11254 non-null   str
 22  Cancelled Rides by Driver          28819 non-null   float64
 23  Driver Cancellation Reason         28819 non-null   str
 24  Incomplete Rides                   9663 non-null    float64
 25  Incomplete Rides Reason            9663 non-null    str
 26  Driver Ratings                     99666 non-null   float64
 27  Customer Rating                    99666 non-null   float64
 28  Payment Method                     109329 non-null  str
dtypes: float64(9), int64(4), str(16)
memory usage: 35.5 MB
None

In [6]:
print(df.isna().sum())

datetime                                  0
Date                                      0
Time                                      0
year                                      0
month                                     0
day                                       0
weekday                                   0
hour                                      0
ride_date                                 0
Event                                     0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Ride Distance                         51280
Booking Value                         51280
Avg VTAT                              11207
Avg CTAT                              51280
Cancelled Rides by Customer          149355
Reason for cancelling by Customer    149355
Cancelled Rides by Driver            131790
Driver Cancellation Reason           131790
Incomplete Rides                     150946
Incomplete Rides Reason              150946
Driver Ratings                        60943
Customer Rating                       60943
Payment Method                        51280
dtype: int64

In [7]:
print("Duplicated Rows:",df.duplicated().sum())

Duplicated Rows: 1006

In [8]:
print("Columns in the Dataset:",df.columns.tolist())
print(df.dtypes)

Columns in the Dataset: ['datetime', 'Date', 'Time', 'year', 'month', 'day', 'weekday', 'hour', 'ride_date', 'Event', 'Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Ride Distance', 'Booking Value', 'Avg VTAT', 'Avg CTAT', 'Cancelled Rides by Customer', 'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason', 'Driver Ratings', 'Customer Rating', 'Payment Method']
datetime                                 str
Date                                     str
Time                                     str
year                                   int64
month                                  int64
day                                    int64
weekday                                  str
hour                                   int64
ride_date                                str
Event                                    str
Booking ID                               str
Booking Status                           str
Customer ID                              str
Vehicle Type                             str
Pickup Location                          str
Drop Location                            str
Ride Distance                        float64
Booking Value                        float64
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer        str
Cancelled Rides by Driver            float64
Driver Cancellation Reason               str
Incomplete Rides                     float64
Incomplete Rides Reason                  str
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                           str
dtype: object

In [9]:
df["datetime"].head()

0    2024-03-23 12:29:38
1    2024-11-29 18:01:39
2    2024-08-23 08:56:10
3    2024-10-21 17:17:25
4    2024-09-16 22:08:00
Name: datetime, dtype: str

In [10]:
"Missing datetime:",df["datetime"].isna().sum()

('Missing datetime:', np.int64(0))

In [11]:
"Missing values in:\n",df[["Date","Time","ride_date"]].isna().sum()

('Missing values in:\n',
 Date         0
 Time         0
 ride_date    0
 dtype: int64)

In [12]:
df["Booking Status"].value_counts()

Booking Status
Completed                99666
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Incomplete                9663
Name: count, dtype: int64

In [13]:
df["Vehicle Type"].value_counts()

Vehicle Type
Auto             40066
Go Mini          31873
Go Sedan         29042
Bike             24108
Premier Sedan    19453
eBike            11285
Uber XL           4782
Name: count, dtype: int64

In [14]:
print("Unique Pickup Locations:",df["Pickup Location"].value_counts().count())
df["Pickup Location"].value_counts()

Unique Pickup Locations: 176

Pickup Location
Khandsa             1018
Barakhamba Road     1018
Mehrauli            1007
AIIMS                994
Badarpur             991
                    ...
Ghitorni Village     852
Laxmi Nagar          849
Mandi House          848
Chirag Delhi         848
Noida Sector 18      842
Name: count, Length: 176, dtype: int64

In [15]:
print("Unique Drop Locations:",df["Drop Location"].value_counts().count())
df["Drop Location"].value_counts()

Unique Drop Locations: 176

Drop Location
Ashram              999
Shastri Nagar       986
Basai Dhankot       979
Moolchand           978
Cyber Hub           977
                   ...
Bhiwadi             850
Seelampur           849
Shivaji Park        846
Anand Vihar ISBT    839
Huda City Centre    822
Name: count, Length: 176, dtype: int64

In [16]:
print("Unique Event Values:",df["Event"].value_counts().count())
df["Event"].value_counts()

Unique Event Values: 16

Event
Normal Day          73084
Wedding_Season      33173
Monsoon             31838
Navratri             6673
Monsoon_Sales        6318
Diwali               2466
Festive_Sales        2058
Eid-ul-Adha           834
Eid-ul-Fitr           833
Christmas             796
Dussehra              458
Republic Day          452
Gandhi Jayanti        425
New Year              416
Independence Day      404
Holi                  381
Name: count, dtype: int64

In [17]:
print("Number of cancelled rides by customer:",df["Cancelled Rides by Customer"].value_counts().sum())
df["Cancelled Rides by Customer"].value_counts()

Number of cancelled rides by customer: 11254

Cancelled Rides by Customer
1.0    11254
Name: count, dtype: int64

In [18]:
print("Unique Cacellation reason by customer:",df["Reason for cancelling by Customer"].value_counts().count())
df["Reason for cancelling by Customer"].value_counts()

Unique Cacellation reason by customer: 5

Reason for cancelling by Customer
Change of plans                                 2531
Wrong Address                                   2515
Driver is not moving towards pickup location    2512
Driver asked to cancel                          2452
AC is not working                               1244
Name: count, dtype: int64

In [19]:
print("Number of rides cancelled by drivers:",df["Cancelled Rides by Driver"].value_counts().sum())
df["Cancelled Rides by Driver"].value_counts()

Number of rides cancelled by drivers: 28819

Cancelled Rides by Driver
1.0    28819
Name: count, dtype: int64

In [20]:
print("Unique Cacellation reason by driver:",df["Driver Cancellation Reason"].value_counts().count())
df["Driver Cancellation Reason"].value_counts()

Unique Cacellation reason by driver: 4

Driver Cancellation Reason
Customer related issue                 7282
The customer was coughing/sick         7211
Personal & Car related issues          7176
More than permitted people in there    7150
Name: count, dtype: int64

In [21]:
print("Number of incomplete rdies:",df["Incomplete Rides"].value_counts().sum())
df["Incomplete Rides"].value_counts()

Number of incomplete rdies: 9663

Incomplete Rides
1.0    9663
Name: count, dtype: int64

In [22]:
print("Unique Ride Incompletion reason",df["Incomplete Rides Reason"].value_counts().count())
df["Incomplete Rides Reason"].value_counts()

Unique Ride Incompletion reason 3

Incomplete Rides Reason
Customer Demand      3268
Vehicle Breakdown    3236
Other Issue          3159
Name: count, dtype: int64

In [23]:
print("Number of unique payment methods:",df["Payment Method"].value_counts().count())
df["Payment Method"].value_counts()

Number of unique payment methods: 5

Payment Method
UPI            49223
Cash           27176
Uber Wallet    13151
Credit Card    10959
Debit Card      8820
Name: count, dtype: int64

In [24]:
print("Columns with integer data",df.select_dtypes(int).columns,"\n")
print("Columns with float data:",df.select_dtypes(float).columns,"\n")

Columns with integer data Index(['year', 'month', 'day', 'hour'], dtype='str')

Columns with float data: Index(['Ride Distance', 'Booking Value', 'Avg VTAT', 'Avg CTAT',
       'Cancelled Rides by Customer', 'Cancelled Rides by Driver',
       'Incomplete Rides', 'Driver Ratings', 'Customer Rating'],
      dtype='str')

In [25]:
print("Statistical info of integer datatype columns:\n")
print(df[['year', 'month', 'day', 'hour']].describe())

Statistical info of integer datatype columns:

           year          month            day           hour
count  160609.0  160609.000000  160609.000000  160609.000000
mean     2024.0       6.548232      15.175955      14.032302
std         0.0       3.369327       8.779055       5.414596
min      2024.0       1.000000       1.000000       0.000000
25%      2024.0       4.000000       8.000000      10.000000
50%      2024.0       7.000000      15.000000      15.000000
75%      2024.0       9.000000      23.000000      18.000000
max      2024.0      12.000000      31.000000      23.000000

In [26]:
print("Statistical info of flaot datatype columns:\n")
print(df[['Ride Distance', 'Booking Value', 'Avg VTAT', 'Avg CTAT',
        'Driver Ratings', 'Customer Rating']].describe())

Statistical info of flaot datatype columns:

       Ride Distance  Booking Value       Avg VTAT       Avg CTAT  \
count  109329.000000  109329.000000  149402.000000  109329.000000
mean       24.616326     508.638495       8.452117      29.137421
std        13.999738     396.312667       3.772035       8.907190
min         1.000000      50.000000       2.000000      10.000000
25%        12.430000     234.000000       5.300000      21.600000
50%        23.670000     414.000000       8.300000      28.700000
75%        36.790000     689.000000      11.300000      36.800000
max        50.000000    4277.000000      20.000000      45.000000

       Driver Ratings  Customer Rating
count    99666.000000     99666.000000
mean         4.230682         4.404499
std          0.436971         0.437776
min          3.000000         3.000000
25%          4.100000         4.200000
50%          4.300000         4.500000
75%          4.600000         4.800000
max          5.000000         5.000000

In [27]:
"Missing value in columns:\n",df[["Ride Distance", "Booking Value", "Avg VTAT", "Avg CTAT", "Driver Ratings","Customer Rating"]].isna().sum()

('Missing value in columns:\n',
 Ride Distance      51280
 Booking Value      51280
 Avg VTAT           11207
 Avg CTAT           51280
 Driver Ratings     60943
 Customer Rating    60943
 dtype: int64)

In [28]:
print("Booking Status distribution only for the rows where Ride Distance is missing:")
df["Booking Status"].where(df["Ride Distance"].isna()).value_counts()

Booking Status distribution only for the rows where Ride Distance is missing:

Booking Status
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Name: count, dtype: int64

In [29]:
print("Booking Status distribution for rows where Booking Value is missing:")
df["Booking Status"].where(df["Booking Value"].isna()).value_counts()

Booking Status distribution for rows where Booking Value is missing:

Booking Status
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Name: count, dtype: int64

In [30]:
print("Booking Status distribution among rows where Avg CTAT is missing:")
df["Booking Status"].where(df["Avg CTAT"].isna()).value_counts()

Booking Status distribution among rows where Avg CTAT is missing:

Booking Status
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Name: count, dtype: int64

In [31]:
print("Booking Status distribution among rows where Avg VTAT is missing:")
df["Booking Status"].where(df["Avg VTAT"].isna()).value_counts()

Booking Status distribution among rows where Avg VTAT is missing:

Booking Status
No Driver Found    11207
Name: count, dtype: int64

In [32]:
print("Booking Status distribution for rows where Driver Ratings is missing:")
df["Booking Status"].where(df["Driver Ratings"].isna()).value_counts()

Booking Status distribution for rows where Driver Ratings is missing:

Booking Status
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Incomplete                9663
Name: count, dtype: int64

In [33]:
print("Booking Status distribution for rows where Customer Rating is missing:")
df["Booking Status"].where(df["Customer Rating"].isna()).value_counts()

Booking Status distribution for rows where Customer Rating is missing:

Booking Status
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Incomplete                9663
Name: count, dtype: int64

In [34]:
print("Checking missing values for important catrgorical columns:")
df[["Booking Status","Vehicle Type","Pickup Location","Drop Location","Event","Payment Method"]].isna().sum()

Checking missing values for important catrgorical columns:

Booking Status         0
Vehicle Type           0
Pickup Location        0
Drop Location          0
Event                  0
Payment Method     51280
dtype: int64

In [35]:
print("Columns with missing data:")
df.isna().sum()[df.isna().sum()>0]

Columns with missing data:

Ride Distance                         51280
Booking Value                         51280
Avg VTAT                              11207
Avg CTAT                              51280
Cancelled Rides by Customer          149355
Reason for cancelling by Customer    149355
Cancelled Rides by Driver            131790
Driver Cancellation Reason           131790
Incomplete Rides                     150946
Incomplete Rides Reason              150946
Driver Ratings                        60943
Customer Rating                       60943
Payment Method                        51280
dtype: int64

In [36]:
(df["Booking Status"]!=df["Booking Status"].str.strip()).sum()

np.int64(0)

In [37]:
df["Booking Status"].value_counts()

Booking Status
Completed                99666
Cancelled by Driver      28819
Cancelled by Customer    11254
No Driver Found          11207
Incomplete                9663
Name: count, dtype: int64

In [38]:
print("Checking unexpected capitalization:")
df.groupby(df["Booking Status"].str.lower())["Booking Status"].unique()

Checking unexpected capitalization:

Booking Status
cancelled by customer    [Cancelled by Customer]
cancelled by driver        [Cancelled by Driver]
completed                            [Completed]
incomplete                          [Incomplete]
no driver found                [No Driver Found]
Name: Booking Status, dtype: object

In [39]:
print("Checking white sapces in Pickup Location:",(df["Pickup Location"]!=df["Pickup Location"].str.strip()).sum())
print("Checking white sapces in Drop Location:",(df["Drop Location"]!=df["Drop Location"].str.strip()).sum())

Checking white sapces in Pickup Location: 0
Checking white sapces in Drop Location: 0

In [40]:
print("Checking for white spaces in Vehicle Type:",(df["Vehicle Type"]!=df["Vehicle Type"].str.strip()).sum())
print("Checking for white spaces in Event:",(df["Event"]!=df["Event"].str.strip()).sum())
print("Checking for white spaces in Payment Method:",(df["Payment Method"]!=df["Payment Method"].str.strip()).sum())
print("Checking for white spaces in Reason for cancellation by customer:",(df["Reason for cancelling by Customer"]!=df["Reason for cancelling by Customer"].str.strip()).sum())
print("Checking for white spaces in Reason for cancellation by driver:",(df["Driver Cancellation Reason"]!=df["Driver Cancellation Reason"].str.strip()).sum())
print("Checking for white spaces in Reason for incomplete rides:",(df["Incomplete Rides Reason"]!=df["Incomplete Rides Reason"].str.strip()).sum())

Checking for white spaces in Vehicle Type: 0
Checking for white spaces in Event: 0
Checking for white spaces in Payment Method: 51280
Checking for white spaces in Reason for cancellation by customer: 149355
Checking for white spaces in Reason for cancellation by driver: 131790
Checking for white spaces in Reason for incomplete rides: 150946

Here actually there are no whitespaces but as there are missing values NaN!=NaN does not evaluate to False so it get counted in it

In [41]:
print("Checking impossible values for Ride Distance")
print("Max Value",df["Ride Distance"].max())
print("Min Value",df["Ride Distance"].min())

Checking impossible values for Ride Distance
Max Value 50.0
Min Value 1.0

In [42]:
print("Checking impossible values for Booking Value")
print("Max Value",df["Booking Value"].max())
print("Min Value",df["Booking Value"].min())

Checking impossible values for Booking Value
Max Value 4277.0
Min Value 50.0

In [43]:
print("Checking impossible values for Avg VTAT")
print("Max Value",df["Avg VTAT"].max())
print("Min Value",df["Avg VTAT"].min())

Checking impossible values for Avg VTAT
Max Value 20.0
Min Value 2.0

In [44]:
print("Checking impossible values for Avg CTAT")
print("Max Value",df["Avg CTAT"].max())
print("Min Value",df["Avg CTAT"].min())

Checking impossible values for Avg CTAT
Max Value 45.0
Min Value 10.0

In [45]:
print("Checking impossible values for Driver Ratings")
print("Max Value",df["Driver Ratings"].max())
print("Min Value",df["Driver Ratings"].min())
print("Checking impossible values for Customer Rating")
print("Max Value",df["Customer Rating"].max())
print("Min Value",df["Customer Rating"].min())

Checking impossible values for Driver Ratings
Max Value 5.0
Min Value 3.0
Checking impossible values for Customer Rating
Max Value 5.0
Min Value 3.0

In [46]:
print("Find the unique non-missing values in")
print(df["Cancelled Rides by Customer"].value_counts())
print(df["Cancelled Rides by Driver"].value_counts())
print(df["Incomplete Rides"].value_counts())

Find the unique non-missing values in
Cancelled Rides by Customer
1.0    11254
Name: count, dtype: int64
Cancelled Rides by Driver
1.0    28819
Name: count, dtype: int64
Incomplete Rides
1.0    9663
Name: count, dtype: int64

In [47]:
print("Checking for duplicated ID's in Booking ID")
print(df["Booking ID"].duplicated().sum())
print("Checking for duplicated ID's in Customer ID")
print(df["Customer ID"].duplicated().sum())

Checking for duplicated ID's in Booking ID
11842
Checking for duplicated ID's in Customer ID
11821

In [82]:
print("Investigating duplicated Booking IDs")
a=df[df["Booking ID"].duplicated(keep=False)].head()
print(a)
print("Duplicated Booking IDs")
a["Booking ID"]

Investigating duplicated Booking IDs
               datetime        Date      Time  year  month  day    weekday  \
16  2024-07-01 10:51:16  2024-07-01  10:51:16  2024      7    1     Monday
17  2024-07-01 10:51:16  2024-07-01  10:51:16  2024      7    1     Monday
35  2024-07-13 19:53:15  2024-07-13  19:53:15  2024      7   13   Saturday
36  2024-07-13 19:53:15  2024-07-13  19:53:15  2024      7   13   Saturday
39  2024-10-02 03:10:35  2024-10-02  03:10:35  2024     10    2  Wednesday

    hour   ride_date           Event  ... Avg CTAT  \
16    10  2024-07-01   Monsoon_Sales  ...     27.5
17    10  2024-07-01         Monsoon  ...     27.5
35    19  2024-07-13   Monsoon_Sales  ...      NaN
36    19  2024-07-13         Monsoon  ...      NaN
39     3  2024-10-02  Gandhi Jayanti  ...     30.0

   Cancelled Rides by Customer Reason for cancelling by Customer  \
16                         NaN                               NaN
17                         NaN                               NaN
35                         NaN                               NaN
36                         NaN                               NaN
39                         NaN                               NaN

   Cancelled Rides by Driver Driver Cancellation Reason Incomplete Rides  \
16                       NaN                        NaN              NaN
17                       NaN                        NaN              NaN
35                       1.0     Customer related issue              NaN
36                       1.0     Customer related issue              NaN
39                       NaN                        NaN              NaN

    Incomplete Rides Reason  Driver Ratings  Customer Rating  Payment Method
16                      NaN             4.9              4.3             UPI
17                      NaN             4.9              4.3             UPI
35                      NaN             NaN              NaN             NaN
36                      NaN             NaN              NaN             NaN
39                      NaN             4.4              4.6             UPI

[5 rows x 29 columns]
Duplicated Booking IDs

16    "CNR3221338"
17    "CNR3221338"
35    "CNR8087051"
36    "CNR8087051"
39    "CNR7401001"
Name: Booking ID, dtype: str

In [102]:
print("Investigating Booking ID CNR3221338:")
(df["Booking ID"]=="\"CNR3221338\"").sum()

Investigating Booking ID CNR3221338:

np.int64(2)

In [ ]:
print(df[df["Booking ID"]=="\"CNR3221338\""].duplicated())
df[df["Booking ID"]=="\"CNR3221338\""]

16    False
17    False
dtype: bool

,datetime,Date,Time,year,month,day,weekday,hour,ride_date,Event,...,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating,Payment Method
16,2024-07-01 10:51:16,2024-07-01,10:51:16,2024,7,1,Monday,10,2024-07-01,Monsoon_Sales,...,27.5,NaN,NaN,NaN,NaN,NaN,NaN,4.9,4.3,UPI
17,2024-07-01 10:51:16,2024-07-01,10:51:16,2024,7,1,Monday,10,2024-07-01,Monsoon,...,27.5,NaN,NaN,NaN,NaN,NaN,NaN,4.9,4.3,UPI

In [111]:
print("Duplicated Entries:")
df.duplicated().sum()

Duplicated Entries:

np.int64(1006)

In [115]:
df[df.duplicated()].head(10)

,datetime,Date,Time,year,month,day,weekday,hour,ride_date,Event,...,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating,Payment Method
126,2024-07-21 10:45:00,2024-07-21,10:45:00,2024,7,21,Sunday,10,2024-07-21,Monsoon,...,NaN,1.0,Driver asked to cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,2024-06-16 10:12:54,2024-06-16,10:12:54,2024,6,16,Sunday,10,2024-06-16,Eid-ul-Adha,...,18.5,NaN,NaN,NaN,NaN,NaN,NaN,4.6,4.0,UPI
746,2024-05-31 14:34:29,2024-05-31,14:34:29,2024,5,31,Friday,14,2024-05-31,Normal Day,...,27.8,NaN,NaN,NaN,NaN,NaN,NaN,4.3,4.5,Cash
847,2024-07-05 17:21:56,2024-07-05,17:21:56,2024,7,5,Friday,17,2024-07-05,Monsoon_Sales,...,16.2,NaN,NaN,NaN,NaN,NaN,NaN,4.2,4.5,UPI
848,2024-07-05 17:21:56,2024-07-05,17:21:56,2024,7,5,Friday,17,2024-07-05,Monsoon,...,16.2,NaN,NaN,NaN,NaN,NaN,NaN,4.2,4.5,UPI
1215,2024-10-18 11:56:25,2024-10-18,11:56:25,2024,10,18,Friday,11,2024-10-18,Normal Day,...,NaN,1.0,Wrong Address,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1370,2024-05-21 12:39:47,2024-05-21,12:39:47,2024,5,21,Tuesday,12,2024-05-21,Normal Day,...,NaN,NaN,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN
1527,2024-01-22 11:23:00,2024-01-22,11:23:00,2024,1,22,Monday,11,2024-01-22,Normal Day,...,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN
1730,2024-12-22 07:53:47,2024-12-22,07:53:47,2024,12,22,Sunday,7,2024-12-22,Normal Day,...,33.4,NaN,NaN,NaN,NaN,NaN,NaN,3.5,3.6,Uber Wallet
1839,2024-11-04 18:24:53,2024-11-04,18:24:53,2024,11,4,Monday,18,2024-11-04,Normal Day,...,38.2,NaN,NaN,NaN,NaN,NaN,NaN,4.6,4.6,UPI

In [132]:
print("Rows that will remain after deleting duplicated rows keeping the first occurence:")
df[~df.duplicated(keep="first")].shape[0]

Rows that will remain after deleting duplicated rows keeping the first occurence:

159603

In [137]:
print("Cleaned data set(removed exact duplicates)")
df_clean=df[~df.duplicated(keep="first")]
df_clean.head()

Cleaned data set(removed exact duplicates)

,datetime,Date,Time,year,month,day,weekday,hour,ride_date,Event,...,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23 12:29:38,2024-03-23,12:29:38,2024,3,23,Saturday,12,2024-03-23,Normal Day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29 18:01:39,2024-11-29,18:01:39,2024,11,29,Friday,18,2024-11-29,Wedding_Season,...,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,NaN,NaN,UPI
2,2024-08-23 08:56:10,2024-08-23,08:56:10,2024,8,23,Friday,8,2024-08-23,Monsoon,...,25.8,NaN,NaN,NaN,NaN,NaN,NaN,4.9,4.9,Debit Card
3,2024-10-21 17:17:25,2024-10-21,17:17:25,2024,10,21,Monday,17,2024-10-21,Normal Day,...,28.5,NaN,NaN,NaN,NaN,NaN,NaN,4.6,5.0,UPI
4,2024-09-16 22:08:00,2024-09-16,22:08:00,2024,9,16,Monday,22,2024-09-16,Normal Day,...,19.6,NaN,NaN,NaN,NaN,NaN,NaN,4.1,4.3,UPI

In [140]:
a=df_clean.duplicated().sum()
print("Duplicated values in cleaned data set:",a)

Duplicated values in cleaned data set: 0